### ISSUE TITLE
Problem with "use rustc_serialize::base64::{ToBase64,STANDARD};"

### ISSUE THREAD

**Issue by cryptsec** [tintinweb/ecdsa-private-key-recovery#1]
Hi,
Can you change your code because "use rustc_serialize :: base64 :: {To Base64, STANDARD};" is deprecated and data is not converted to hex ...
Thanks.

**Comment by tintinweb** [comment]
Hi @cryptsec,

good reminder to upload the rest of my scripts so that you can actually play with that stuff. Need to do some cleanup first. Expect it in the next days or so.

cheers

**Comment by tintinweb** [comment]
Uploaded my hacky rusty-blockparser to mysql import script https://github.com/tintinweb/ecdsa-private-key-recovery/commit/3b9d6019b7c6c746be94fb8b06778bc647f89385 . Will upload the privkey recovery script later. I'll close this issue for now as it is kind of misleading. Feel free to open another issue with a precise description of what you're trying to achieve.

cheers

**Comment by LazyGeek-dev** [comment]
Hi, Need Help with rustyblockparser !  
Can you please update the full modified version of your csvdump.rs code ? 

Thanks
