### ISSUE TITLE
ECDSA Parameters

### ISSUE THREAD

**Issue by tiagomendes7** [tintinweb/ecdsa-private-key-recovery#10]
I am trying to extract the ECDSA parameters from the bitcoin blockchain.

I tried reading your code but couldnt understand where you obtain the hash of the message and the publick key. Could you tell me in each file and the lines where that is done ?

**Comment by tintinweb** [comment]
https://github.com/tintinweb/ecdsa-private-key-recovery/blob/master/tools/bitcoin/bitcrack.py#L334

**Comment by tiagomendes7** [comment]
Hi,

Thank you .


Obrigado,
os meus cumprimentos

Tiago Mendes
tiagovazmendes7@gmail.com

**Comment by tintinweb** [comment]
you're welcome

**Comment by tiagomendes7** [comment]
Hi,

Your function does not work for multi-sim transacionas does it ?

Obrigado,
os meus cumprimentos

Tiago Mendes
tiagovazmendes7@gmail.com
