### ISSUE TITLE
TinTin.... 

### ISSUE THREAD

**Issue by mikejnpc** [tintinweb/ecdsa-private-key-recovery#13]
Is there a method availble for recovery if you have the nonce, keyspace, pk value ranges, edcsa, pub key and other variables .... in my instance there is only 1 txn out and know the bip creation etc before the 2014 division.......

**Comment by tintinweb** [comment]
if you can narrow it down to private key candidates then yes. if you only have one signed tx but no information to narrow down the secret then now.
