### ISSUE TITLE
Hey. The script gives an error.

### ISSUE THREAD

**Issue by hunaman** [tintinweb/ecdsa-private-key-recovery#3]
python bitcrack.py
Traceback (most recent call last):
  File "bitcrack.py", line 32, in <module>
    from ecdsa_key_recovery import EcDsaSignature
ImportError: No module named ecdsa_key_recovery
What do I need to install to make it work?

**Comment by tintinweb** [comment]
hey @hunaman,

`python setup.py install` or have the programm working dir =  this repo.

**Comment by hunaman** [comment]
Where do I get setup.py? Send me a link to the file. The repository does not have this setup.py file..

**Comment by tintinweb** [comment]
@hunaman seems like I forgot to add the setup.py :) just added it with https://github.com/tintinweb/ecdsa-private-key-recovery/commit/44e39d762d2b605512d99a380f54ff408a2adeb1

cheers.
