### ISSUE TITLE
error

### ISSUE THREAD

**Issue by hamnaz** [tintinweb/ecdsa-private-key-recovery#4]
./python bitcrack.py import tx_in.csv.tmp
Traceback (most recent call last):
  File "bitcrack.py", line 35, in <module>
    from bitcoinrpc.authproxy import AuthServiceProxy, JSONRPCException
ImportError: No module named bitcoinrpc.authproxy

**Comment by tintinweb** [comment]
Hi @hamnaz,

`#>pip install python-bitcoinrpc` 

cheers,
tin
