### ISSUE TITLE
Issue with Import - Padding Error

### ISSUE THREAD

**Issue by gmk89** [tintinweb/ecdsa-private-key-recovery#5]
Hello, I recieved a padding error when import tx_in.csv.tmp.  I tried changing part of the script to use a base64 decode package and received the same error. Any idea with what's causing it?

```
ae3f20b62842d769041ce666064c8b5ac85bfa291529aff4bd2a2c23cafd93a0 TypeError(Error('Incorrect padding',),)
Traceback (most recent call last):
  File "bitcrack.py", line 762, in <module>
    import_csv_to_mysql(args[1])
  File "bitcrack.py", line 733, in import_csv_to_mysql
    logger.warning(sig['nr'])
UnboundLocalError: local variable 'sig' referenced before assignment
```

**Comment by Nikoloves** [comment]
...the same problem...some idea, please

**Comment by carloseduedu** [comment]
The same error message for me, does anyone know if there is already a solution reported? can you help me? Thank you

**Comment by tintinweb** [comment]
@gmk89 
fixed the initial error with `UnboundLocalError: local variable 'sig' referenced before assignment`. This was a debug leftover. the exception was raised after the data has been committed to the database.

@Nikoloves - this appears to be a different issue.
